name: Build Aplicacao Java

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
    inputs:
      release:
        description: Versão da Release
        required: false
        type: string


jobs:
  Build:
    runs-on: eich
    env:
      APPLICATION: ${{ vars.application }}
      VERSION: ${{ inputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: eich-template-actions/template-action-sast/.github/actions/sast@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
      - name: Compile Application
        run: |
          echo "Compilando a Imagem $APPLICATION:$VERSION";
          docker build -t $APPLICATION:$VERSION .;
      - name: Push Image
        if: ${{ inputs.release }}
        env:
          CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
        run: kind load docker-image $APPLICATION:$VERSION --name $CLUSTER_NAME
      - name: Upload do Helm como artefato
        uses: actions/upload-artifact@v4
        with:
          name: helm
          path: helm
          retention-days: 0

  Apply-Local:
    runs-on: eich
    environment: local
    needs: Build
    if: ${{ inputs.release }}
    steps:
      - name: Apply
        env:
          APPLICATION: ${{ vars.application }}
          NAMESPACE: ${{ vars.namespace }}
          VERSION: ${{ inputs.release }}
        run: |
          helm upgrade --install $APPLICATION helm/$APPLICATION/ -n app-$NAMESPACE --set image.tag="$VERSION" --create-namespace
          echo "Aplicado: $TESTE";
      
  limpeza:
    if: always()
    needs: Apply-Local
    runs-on: eich
    steps:
      - name: Limpar
        uses: eich-template-actions/template-action-limpeza/actions/limpeza@master